### ISSUE TITLE
Find polish versions of the articles on gravitational waves

### ISSUE THREAD

**Issue by deshipu** [deshipu/microbit-micropython-pl#1]
In `tutorials/introduction.rst` there are two links to articles about the discovery of gravitational waves. However, there are no Polish versions of those articles available. I think we should find similar articles on Polish services (which ones?) and use those instead.

**Comment by pawel-lewtak** [comment]
I'm afraid no Polish article mentions Python but why not use this one for gravitational waves discovery? http://www.focus.pl/kosmos/fale-grawitacyjne-zmierzone-po-raz-pierwszy-13703
